apiVersion: v1
kind: Service
metadata:
  name: kube-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 6060
  selector:
    app: hello-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes-one
        image: sanartifactory.jfrog.io/artifactory/docker-local/hello-kubernetes:latest
        ports:
        - containerPort: 8080
