apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzYW5hcnRpZmFjdG9yeS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYzJGdWRHaHZjMmh5WldSa2VYQmhjbUZ3WVhScExuUnlRR2R0WVdsc0xtTnZiVG8zTkRJeU1URkFWbUZ1IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy4xMiAobGludXgpIgoJfQp9
kind: Secret
metadata:  
  name: regcred
type: kubernetes.io/dockerconfigjson